#!/bin/bash
. $GANNET_DIR/etc/gannetrc
MODEL_NAME="haloExchange3DRealExample"
PROC_PER_ROW=4
PROC_PER_COL=3
INSTANCES=$(($PROC_PER_ROW * $PROC_PER_COL))
mkdir -p src/GMCF/Models
mkdir -p gensrc/GMCF/Models
python ../../GMCF_Utilities/connectvity_matrix_generator.py "$PROC_PER_ROW" "$PROC_PER_COL" > src/GMCF/Models/gmcfConfiguration.f95
python ../../GMCF_Utilities/td_generator.py "$INSTANCES" "$MODEL_NAME" > "$MODEL_NAME".td
python ../../GMCF_Utilities/yml_generator.py "$INSTANCES" "$MODEL_NAME" > "$MODEL_NAME".yml
build.pl -Y "$MODEL_NAME.yml" -L
scons -f SConstruct."$MODEL_NAME"

